### ISSUE TITLE
gatsby-remark-normalize-paths for frontmatter gallery

### ISSUE THREAD

**Issue by jacknevitt** [kendallstrautman/brevifolia-gatsby-forestry#7]
Hello Kendall, thanks for putting this demo together, I've found it really helpful to get my project running, however my frontmatter gallery paths are not being normalized (I think). My project is a private repo so I can't share what I've done. It's based off the gatsby starter with forestry as my cms also.
Could you share how you got `childImageSharp` to show for your `hero_image` in the graphQL server? I'd like to get the same working for my gallery image paths!
Many thanks!
Jack

**Comment by karimaBZ** [comment]
I have the same problem :'( any help please

**Comment by DirtyF** [comment]
@jacknevitt The query is here: https://github.com/kendallstrautman/brevifolia-gatsby-forestry/blob/d8937c74d47ea7e7ebe0143dbebbce02df3831a1/src/static_queries/useBlogData.js#L14-L20

**Comment by karimaBZ** [comment]
@DirtyF in my case I get this error **GraphQL Error Field "hero_image" must not have a selection since type "String" has no subfields.**

**Comment by kendallstrautman** [comment]
I'll need more information about what you're trying to do. When I pull a fresh clone of this repo, it runs fine. And when I upload a new hero image to a blog post from forestry, the path is correct. Could you provide more specific details as to the problem you are seeing, the versions of the packages that could contribute to this problem etc?

**Comment by kendallstrautman** [comment]
After some digging, I think I understand better what you are asking. I would refer to [this spectrum conversation](https://spectrum.chat/gatsby-js/general/using-variables-in-a-staticquery~abee4d1d-6bc4-4202-afb2-38326d91bd05) for some ideas on how to query multiple images at once. It could look something like this 

```js
export default function useAllImages() {
  const images = useStaticQuery(graphql`
    query getImages {
      allFile(filter: { extension: { regex: "/jpeg|jpg|png|gif/" } }) {
        edges {
          node {
            relativePath
            childImageSharp {
              fluid {
                ...GatsbyImageSharpFluid
              }
            }
          }
        }
      }
    }
  `)
  return images.allFile.edges
}

```
And then you could filter through those images based on the paths in the source data: 

```jsx
 const allImages = useAllImages()

  const galleryImages = data.markdownRemark.frontmatter.gallery_images.map(image => {
    // chops off /content/images/
    const currentRelativePath = image.split("/")[3]

    /**  get transformed images by comparing image src
     *  in data file with 'allImages' query data
     */
    return allImages.find(
      image => image.node.relativePath === currentRelativePath
    )
  })
```
